# Generated by Django 3.1.3 on 2020-12-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='creditos',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='materia',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
