# Generated by Django 3.1.3 on 2020-12-03 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=120, verbose_name='Nombres')),
                ('apellidos', models.CharField(blank=True, max_length=120, verbose_name='Apellidos')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, max_length=120, verbose_name='Email')),
                ('activo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['nombre'],
            },
        ),
    ]
